### ISSUE TITLE
Error loading package: No module named 'pathlib'

### ISSUE THREAD

**Issue by dportalesr** [SublimeText/SaneSnippets#16]
I noticed SaneSnippets suddenly stopped working for me. I've already tried reinstalling the package and restarting sublime with no luck. I see this from ST's console so it looks related to python, which I must say, I haven't touched in a while.

```
reloading plugin SaneSnippets.sane_snippets
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/Dan/Library/Application Support/Sublime Text 3/Installed Packages/SaneSnippets.sublime-package/sane_snippets.py", line 3, in <module>
ImportError: No module named 'pathlib'
```

### Environment

Mac OS 10.15.5
SublimeText v3.2.2 build 3211
`$ python --version` => 2.7.15
`$ python3 --version` => 3.7.3

Any advice will be appreciated.

**Comment by FichteFoll** [comment]
Did you install the package through a method other than Package Control? The dependency should get installed as you install SaneSnippets. Try running *Package Control: Satisfy Dependencies* manually and restart ST.

**Comment by FichteFoll** [comment]
Nevermind that, I see the problem now. This is a bug that I'll fix tomorrow.
